package com.base.models;

import com.base.controllers.DBmanager;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

import java.io.Serializable;
import java.sql.Date;


public class Beehives implements Serializable {

    //this is the number that identify the hive. It is not autogenerated and user have to introduce it.
    private int number;

    //this is the id of the apiary to which the hive belongs.
    private int id_apiary;

    //this is the date where hive was starting to be used in an Apiary
    private Date date;

    //this is the type of hive. You have diferent models in the market
    private String type;

    //this tells you if the hive have a disease actually. This parameters is calculated from the table diseases
    private boolean diseased;

    //this parameter is to print in the mainwindow tableview a message if the the beehive is diseased or not.
    private String tableViewDiseased;

    //this parameter is to print in the mainwindow tableview a message if the the beehive is favorite or not.
    private String tableViewFavorite;

    private ObservableList<Diseases> diseasesList;

    private boolean favorite;

    public Beehives() {
        diseasesList = FXCollections.observableArrayList();
    }

    public Beehives(int number, int id_apiary, Date date, String type, boolean diseased, ObservableList<Diseases> diseasesList, boolean favorite) {
        this.number = number;
        this.id_apiary = id_apiary;
        this.date = date;
        this.type = type;
        this.diseased = diseased;
        this.diseasesList = diseasesList;
        this.favorite = favorite;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public int getId_apiary() {
        return id_apiary;
    }

    public void setId_apiary(int id_apiary) {
        this.id_apiary = id_apiary;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public boolean isFavorite() {
        return favorite;
    }

    public void setFavorite(boolean favorite) {
        this.favorite = favorite;
    }

    public boolean isDiseased() {

        Date actualDate = new Date(System.currentTimeMillis());
        getDiseasesList();
        for (Diseases di : diseasesList) {

            if (null != di.getStartingDate() && null == di.getEndingDate()) {
                diseased = true;
                return diseased;
            } else if (null != di.getStartingDate() && null != di.getEndingDate()) {
                if (di.getEndingDate().compareTo(actualDate) > 0) {
                    diseased = true;
                    return diseased;
                }
            } else {
                diseased = false;
            }
        }

        return diseased;
    }


    public ObservableList<Diseases> getDiseasesList() {

        diseasesList.clear();
        diseasesList = DBmanager.getINSTANCE().getDiseases(this);

        return diseasesList;
    }

    public void setDiseasesList(ObservableList<Diseases> diseasesList) {
        this.diseasesList = diseasesList;
    }

    public String getTableViewDiseased() {

        if (isDiseased()) {
            tableViewDiseased = "enferma";
        } else {
            tableViewDiseased = "sana";
        }

        return tableViewDiseased;
    }

    public String getTableViewFavorite() {
        if (isFavorite()) {
            tableViewFavorite = "si";
        } else {
            tableViewFavorite = "";
        }
        return tableViewFavorite;
    }
}
